security:
  oauth2:
    client:
      clientId: 1134145433389601
      clientSecret: 44f03d77602a954753adb10aab0f2dba
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
          hibernate:
            jdbc:
              lob:
                non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost/mercadito
    username: mercado
    password: m3rc4d0
